DROP FUNCTION IF EXISTS is_user_by_id_exists;
DELIMITER //

CREATE FUNCTION is_user_by_id_exists (user_id INT)
RETURNS BOOLEAN READS SQL DATA
BEGIN
  RETURN EXISTS(SELECT 1 FROM users WHERE id = user_id);
END//



DROP PROCEDURE IF EXISTS get_user_profile_by_user_id;
DELIMITER //
CREATE PROCEDURE get_user_info_by_id(id INT)
BEGIN
	SELECT * FROM profiles AS p WHERE p.user_id = id;
END //

DELIMITER //
CREATE TRIGGER articles_insert BEFORE INSERT ON articles
FOR EACH ROW BEGIN
  IF NEW.`text` IS NULL THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'text are NULL';
  END IF;
END//


DELIMITER //
CREATE TRIGGER title_update BEFORE update ON articles
FOR EACH ROW BEGIN
  IF NEW.title IS NULL THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'title are NULL';
  END IF;
END//


DELIMITER //
CREATE TRIGGER email_insert BEFORE INSERT ON users
FOR EACH ROW BEGIN
  IF NEW.email IS NULL THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'email are NULL';
  END IF;
END//
